version: '3.4'

services:
  bfm.diet.web.redis: 
    command: "redis-server /usr/local/etc/redis/redis.conf"
    image: "redis:alpine"
    ports: 
      - "6379:6379"
    restart: on-failure
    volumes: 
      - "./data:/data"
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"

    networks:
      bfm_network:
        ipv4_address: 172.40.0.20
        
  elasticsearch:  
   container_name: elasticsearch  
   image: elasticsearch:7.10.1  
   ports:  
    - 9200:9200  
   volumes:  
    - elasticsearch-data:/usr/share/elasticsearch/data  
   environment:  
    - xpack.monitoring.enabled=true  
    - xpack.watcher.enabled=false  
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  
    - discovery.type=single-node  
   networks:  
     bfm_network:
       ipv4_address: 172.40.0.30 
  
  kibana:  
   container_name: kibana  
   image: kibana:7.10.1  
   ports:  
    - 5601:5601  
   depends_on:  
    - elasticsearch  
   environment:  
    - ELASTICSEARCH_URL=http://localhost:9200  
   networks:  
    bfm_network:
       ipv4_address: 172.40.0.40 
    
  bfm.diet.web.api:
    image: bfmdietwebapi
    build:
      context: .
      dockerfile: Bfm.Diet.Web.Api/Dockerfile
  
volumes:  
  elasticsearch-data:  
  
networks:
  bfm_network:
    ipam:
      driver: default
      config:
        - subnet: 172.40.0.0/16